// ═══════════════════════════════════════════════════════════════════════════
// Desk-worker training program generator.
//
// Rule-based on purpose. The plan a diabetic follows for months should be
// inspectable and reproducible, not regenerated by a language model each time
// it is asked. The AI agents comment on the plan; they do not author it.
//
// Structure follows mainstream physical-activity guidance: ~150 min/week of
// moderate aerobic work, resistance training on 2+ non-consecutive days, and
// — the part that matters specifically for someone at a desk all day —
// breaking up prolonged sitting.
// ═══════════════════════════════════════════════════════════════════════════

import { filterExercises } from './catalog.js';

/** Deterministic PRNG so "today's plan" is stable across reloads. */
function seeded(seed) {
  let s = 0;
  for (let i = 0; i < seed.length; i++) s = (s * 31 + seed.charCodeAt(i)) >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 0x100000000;
  };
}

function pick(rng, arr, n) {
  const pool = [...arr];
  const out = [];
  while (out.length < n && pool.length) {
    out.push(pool.splice(Math.floor(rng() * pool.length), 1)[0]);
  }
  return out;
}

const dayKey = d => new Date(d).toISOString().slice(0, 10);

// ─── Movement snacks ────────────────────────────────────────────────────────

/**
 * Short bouts to interrupt sitting. The evidence for breaking up sedentary
 * time is strongest for post-meal glucose, so the schedule deliberately puts
 * bouts after typical meal times.
 */
export function movementSnacks(index, { date = new Date(), workStart = 9, workEnd = 17, count = null } = {}) {
  const rng = seeded(`snack-${dayKey(date)}`);
  const candidates = filterExercises(index, { deskSnack: true });
  const slots = [];
  const total = count ?? Math.max(1, workEnd - workStart);

  for (let i = 0; i < total; i++) {
    const hour = workStart + i;
    if (hour >= workEnd) break;
    slots.push({ hour, postMeal: hour === 13 || hour === 9 });
  }

  const chosen = pick(rng, candidates, slots.length);
  return slots.map((slot, i) => ({
    hour: slot.hour,
    label: `${String(slot.hour).padStart(2, '0')}:00`,
    durationMin: slot.postMeal ? 10 : 3,
    postMeal: slot.postMeal,
    exercise: chosen[i] || candidates[0] || null,
    why: slot.postMeal
      ? 'A short walk or easy set after eating blunts the post-meal glucose rise.'
      : 'Breaking up sitting keeps the legs working and helps insulin sensitivity.',
  })).filter(s => s.exercise);
}

// ─── Resistance sessions ────────────────────────────────────────────────────

/**
 * Muscle groups a desk job under-uses, in the order they most need attention.
 * Pull before push on purpose: sitting rounds the upper back.
 */
/**
 * Slots are movement PATTERNS, and a pattern is defined by what the body does,
 * not by which muscles light up. Matching on muscles lets a military press
 * satisfy "horizontal pull" because its secondary muscles include the traps —
 * so each slot is matched by name pattern, with muscle used only to break ties.
 */
const DESK_PRIORITY = [
  {
    slot: 'Hinge / posterior chain',
    pattern: /deadlift|hip thrust|good morning|glute bridge|romanian|hyperextension|back extension|kettlebell swing|pull through/i,
    targets: ['glutes', 'hamstrings', 'lower back'],
  },
  {
    slot: 'Horizontal pull',
    pattern: /\brow\b|face pull|reverse fly|rear delt|pullover|pull-over/i,
    exclude: /pull through/i,
    targets: ['upper back', 'rhomboids', 'trapezius', 'traps', 'lats', 'latissimus dorsi'],
  },
  {
    slot: 'Squat / legs',
    pattern: /squat|lunge|split squat|leg extension|leg curl/i,
    exclude: /leg press/i,
    targets: ['quadriceps', 'glutes', 'hamstrings'],
  },
  {
    slot: 'Push',
    pattern: /press|push-?up|\bfly\b|flye/i,
    exclude: /leg press|pull|row/i,
    targets: ['chest', 'deltoids', 'shoulders', 'triceps'],
  },
  {
    slot: 'Core / anti-rotation',
    pattern: /plank|pallof|dead bug|russian twist|hollow|bird dog|side bend|woodchop|anti-rotation/i,
    targets: ['core', 'abdominals', 'obliques'],
  },
  // Sitting all day shortens the hip flexors, so this slot must LENGTHEN them.
  // Mobility only, and it must actually be a stretch — a crunch also "targets
  // hip flexors" and is exactly the wrong prescription here.
  {
    slot: 'Hip mobility',
    pattern: /stretch/i,
    targets: ['hip flexors', 'glutes', 'hamstrings', 'quadriceps'],
    modality: ['mobility'],
  },
];

function matchesTargets(ex, targets) {
  const hay = [ex.target, ex.muscleGroup, ...(ex.secondary || [])].filter(Boolean).map(s => s.toLowerCase());
  return targets.some(t => hay.includes(t));
}

/**
 * An exercise fits a slot when its NAME matches the movement pattern. Muscle
 * agreement is preferred but not required — the pattern is what makes a row a
 * row.
 */
function candidatesForSlot(pool, { pattern, exclude, targets }) {
  const byPattern = pool.filter(ex => pattern.test(ex.name) && !(exclude && exclude.test(ex.name)));
  if (!byPattern.length) return [];
  const alsoRightMuscle = byPattern.filter(ex => matchesTargets(ex, targets));
  return alsoRightMuscle.length ? alsoRightMuscle : byPattern;
}

/**
 * Builds one full-body resistance session.
 *
 * @param {Array}  index
 * @param {object} opts
 * @param {string[]} [opts.equipmentClass]  What the user actually owns.
 * @param {Date}   [opts.date]
 * @param {number} [opts.sets]
 */
export function resistanceSession(index, { equipmentClass = ['none', 'minimal'], ownedEquipment = null, date = new Date(), sets = 3, allowAdvanced = false } = {}) {
  const rng = seeded(`resistance-${dayKey(date)}`);

  // A scanned inventory is authoritative when we have one. Bodyweight is always
  // added back — the scanner is told not to report it, since it is not a thing
  // you can own.
  const equipment = ownedEquipment?.length ? [...new Set([...ownedEquipment, 'body weight'])] : null;

  // A pull-up bar is not a given. Unless the user says they train at a gym,
  // anything the catalog flags as needing apparatus is off the table — upstream
  // labels a pull-up "body weight", which is true and useless.
  const hasGym = equipment
    ? equipment.some(e => ['cable', 'leverage machine', 'smith machine', 'sled machine'].includes(e))
    : equipmentClass.includes('gym');

  const poolFor = modality =>
    filterExercises(index, equipment ? { equipment, modality } : { equipmentClass, modality })
      // Someone starting from a desk job should never be handed a planche.
      .filter(ex => allowAdvanced || !ex.advanced)
      .filter(ex => hasGym || !ex.needsApparatus);

  const blocks = DESK_PRIORITY.map((def) => {
    const { slot, modality = ['resistance'] } = def;
    const matches = candidatesForSlot(poolFor(modality), def);
    // If nothing matches the pattern, skip the slot. Substituting an unrelated
    // exercise (a shoulder press for a row) is worse than a shorter session.
    if (!matches.length) return null;
    const [exercise] = pick(rng, matches, 1);
    return {
      slot,
      exercise,
      sets,
      reps: slot === 'Core / anti-rotation' || slot === 'Hip mobility' ? '30–45s' : '8–12',
      restSec: 90,
    };
  }).filter(Boolean);

  return {
    kind: 'resistance',
    modality: 'resistance',
    title: 'Full-body strength',
    estimatedMin: blocks.length * sets * 2,
    blocks,
    glucoseNote:
      'Resistance work often nudges glucose up during the session, then raises insulin sensitivity for hours. ' +
      'The delayed drop is the one to plan around, especially if you train in the evening.',
  };
}

// ─── Cardio ─────────────────────────────────────────────────────────────────

export function cardioSession({ minutes = 30 } = {}) {
  return {
    kind: 'cardio',
    modality: 'cardio',
    title: 'Easy aerobic (zone 2)',
    estimatedMin: minutes,
    blocks: [
      {
        slot: 'Steady state',
        exercise: null,
        prescription: `${minutes} min at a pace where you can still hold a conversation`,
      },
    ],
    glucoseNote:
      'Steady aerobic work usually pulls glucose down while you do it. Check before you start and keep fast carbs with you.',
  };
}

// ─── Weekly plan ────────────────────────────────────────────────────────────

/**
 * A week that satisfies the aerobic and resistance targets without demanding
 * more than a person with a full-time desk job will actually do.
 *
 * Resistance days are non-consecutive. Evening-heavy weeks are flagged by the
 * correlation engine rather than avoided here — that is the user's call.
 */
export function weeklyPlan(index, { equipmentClass = ['none', 'minimal'], ownedEquipment = null, resistanceDays = 3, startDate = new Date() } = {}) {
  const layout = resistanceDays >= 3
    ? ['resistance', 'cardio', 'resistance', 'rest', 'resistance', 'cardio', 'rest']
    : ['resistance', 'cardio', 'rest', 'resistance', 'cardio', 'rest', 'rest'];

  const start = new Date(startDate);
  const monday = new Date(start);
  monday.setDate(start.getDate() - ((start.getDay() + 6) % 7));

  return layout.map((kind, i) => {
    const date = new Date(monday);
    date.setDate(monday.getDate() + i);
    const session =
      kind === 'resistance' ? resistanceSession(index, { equipmentClass, ownedEquipment, date })
      : kind === 'cardio' ? cardioSession()
      : { kind: 'rest', modality: 'mobility', title: 'Rest / walk', estimatedMin: 0, blocks: [], glucoseNote: '' };

    return {
      date: dayKey(date),
      weekday: date.toLocaleDateString(undefined, { weekday: 'short' }),
      ...session,
    };
  });
}

/** Weekly totals, so the user can see whether the plan actually hits targets. */
export function planSummary(plan) {
  const resistance = plan.filter(d => d.kind === 'resistance').length;
  const cardioMin = plan.filter(d => d.kind === 'cardio').reduce((n, d) => n + d.estimatedMin, 0);
  return {
    resistanceDays: resistance,
    cardioMinutes: cardioMin,
    meetsAerobic: cardioMin >= 150,
    meetsResistance: resistance >= 2,
    note: cardioMin >= 150 && resistance >= 2
      ? 'This week meets the standard weekly activity targets.'
      : 'Below the usual weekly targets — fine while you build the habit.',
  };
}
