// Tests for the browser extension's shared logic (extension/).
//
// The cases that matter most are the ones that decide what a person sees at a glance:
// a low counted only when it lasts 15 minutes, a projection refused when there is too
// little recent data, and a LibreView import that reads US and EU date orders correctly.
// A wrong day/month swap would silently file a month of readings on the wrong dates.

import { describe, it, expect } from 'vitest';
import {
  rangeStats, project, toCsv, mergeSeries, sensorStatus, fmtDuration, fmtDelta, withDefaults, MGDL_PER_MMOL,
} from '../extension/glucose.js';
import { parseLibreViewCsv } from '../extension/libreview-csv.js';
import { wholeSeries, findGaps, coverage } from '../extension/archive.js';
import { parseLibreTime, toPoint } from '../extension/libre.js';

const T0 = Date.UTC(2026, 9, 1, 12);
const minutes = (n, f) => Array.from({ length: n + 1 }, (_, i) => ({ t: T0 + i * 60e3, mg: f(i) }));

describe('rangeStats', () => {
  it('weights each reading by the time it covers', () => {
    const st = rangeStats(minutes(60, (i) => (i < 20 ? 60 : 120)), T0, T0 + 3600e3, 70, 180);
    expect(st.below).toBeCloseTo(20 / 65, 3);
    expect(st.lows).toBe(1);
  });
  it('does not count a dip shorter than 15 minutes as a low', () => {
    expect(rangeStats(minutes(60, (i) => (i < 10 ? 60 : 120)), T0, T0 + 3600e3, 70, 180).lows).toBe(0);
  });
  it('returns null with no data', () => {
    expect(rangeStats([], T0, T0 + 3600e3, 70, 180)).toBeNull();
  });
});

describe('project', () => {
  const rise = minutes(20, (i) => 100 + 2 * i);
  it('extends the recent slope 20 minutes ahead', () => {
    expect(project(rise, rise[20]).mg).toBe(180);
  });
  it('refuses with less than 8 minutes of recent data', () => {
    expect(project(rise.slice(-3), rise[20])).toBeNull();
  });
  it('caps the slope so one noisy reading cannot predict a crash', () => {
    const spike = [...minutes(19, () => 100), { t: T0 + 20 * 60e3, mg: 300 }];
    expect(project(spike, spike[20]).slope).toBeLessThanOrEqual(4);
  });
});

describe('formatting and settings', () => {
  it('formats deltas in both units', () => {
    expect(fmtDelta(-12, 'mg/dL')).toBe('−12');
    expect(fmtDelta(MGDL_PER_MMOL, 'mmol/L')).toBe('+1.0');
  });
  it('formats durations', () => {
    expect(fmtDuration(2 * 864e5 + 3 * 3600e3)).toBe('2d 3h');
    expect(fmtDuration(45 * 60e3)).toBe('45 min');
  });
  it('deep-merges alert defaults so new options reach old installs', () => {
    const s = withDefaults({ alerts: { low: 80 } });
    expect(s.alerts.low).toBe(80);
    expect(s.alerts.urgentLow).toBe(55);
  });
  it('knows when a sensor is warming up, active or ended', () => {
    const now = Date.now();
    expect(sensorStatus({ start: now - 30 * 60e3 }, 14).kind).toBe('warming');
    expect(sensorStatus({ start: now - 13.5 * 864e5 }, 14).kind).toBe('active');
    expect(sensorStatus({ start: now - 15 * 864e5 }, 14).kind).toBe('ended');
    expect(sensorStatus({ start: now - 14.5 * 864e5 }, 15).kind).toBe('active');
  });
});

describe('series merging', () => {
  it('prefers a live minute reading over history within 3 minutes', () => {
    const m = mergeSeries([[T0, 100], [T0 + 5 * 60e3, 110]], [[T0 + 60e3, 101]]);
    expect(m.map((p) => p.mg)).toEqual([101, 110]);
  });
  it('drops archived history and imports next to live readings', () => {
    const recs = [{ t: T0, mg: 100, src: 'hist' }, { t: T0 + 60e3, mg: 101, src: 'live' }, { t: T0 + 10 * 60e3, mg: 120, src: 'import' }];
    expect(wholeSeries(recs).map((p) => p.mg)).toEqual([101, 120]);
  });
  it('finds gaps and measures coverage', () => {
    const gaps = findGaps([{ t: T0 }, { t: T0 + 5 * 60e3 }, { t: T0 + 3 * 3600e3 }], 3600e3, T0 + 3 * 3600e3 + 60e3);
    expect(gaps).toEqual([{ from: T0 + 5 * 60e3, to: T0 + 3 * 3600e3 }]);
    expect(coverage([{ t: T0 }, { t: T0 + 15 * 60e3 }], T0 + 60 * 60e3)).toBeCloseTo(0.5, 2);
  });
});

describe('LibreLinkUp parsing', () => {
  it('reads FactoryTimestamp as UTC', () => {
    expect(parseLibreTime('10/1/2026 2:05:31 PM')).toBe(Date.UTC(2026, 9, 1, 14, 5, 31));
    expect(parseLibreTime('10/1/2026 12:00:00 AM')).toBe(Date.UTC(2026, 9, 1, 0, 0, 0));
  });
  it('converts mmol/L readings when mg/dL is missing', () => {
    const p = toPoint({ FactoryTimestamp: '10/1/2026 2:05:31 PM', Value: 5.5, GlucoseUnits: 0, TrendArrow: 3 });
    expect(p.mg).toBe(Math.round(5.5 * MGDL_PER_MMOL));
    expect(p.trend).toBe(3);
  });
});

describe('LibreView CSV import', () => {
  it('reads the US export (month first, 12-hour clock) with markers', () => {
    const csv = [
      'Glucose Data,Generated on,10-01-2026 2:05 PM UTC,Generated by,Test User',
      'Device,Serial Number,Device Timestamp,Record Type,Historic Glucose mg/dL,Scan Glucose mg/dL,Non-numeric Rapid-Acting Insulin,Rapid-Acting Insulin (units),Non-numeric Food,Carbohydrates (grams),Carbohydrates (servings),Non-numeric Long-Acting Insulin,Long-Acting Insulin Value (units),Notes',
      'FreeStyle Libre 3,ABC,09-28-2026 11:59 PM,0,142,,,,,,,,,',
      'FreeStyle Libre 3,ABC,09-29-2026 12:14 AM,0,138,,,,,,,,,',
      'FreeStyle Libre 3,ABC,09-29-2026 07:30 AM,4,,,,5,,,,,,',
      'FreeStyle Libre 3,ABC,09-29-2026 07:31 AM,5,,,,,,40,,,,',
      'FreeStyle Libre 3,ABC,09-13-2026 01:05 PM,1,,99,,,,,,,,"note, with comma"',
    ].join('\r\n');
    const { readings, events } = parseLibreViewCsv(csv);
    expect(readings).toHaveLength(3);
    const first = new Date(readings.find((r) => r.mg === 142).t);
    expect([first.getMonth(), first.getDate(), first.getHours(), first.getMinutes()]).toEqual([8, 28, 23, 59]);
    expect(events).toEqual(expect.arrayContaining([
      expect.objectContaining({ type: 'insulin', amount: 5 }),
      expect.objectContaining({ type: 'meal', amount: 40 }),
    ]));
  });
  it('reads the EU export (semicolons, day first, mmol/L, decimal comma)', () => {
    const csv = 'Glucosedaten;Erstellt am;01-10-2026\nGerät;Seriennummer;Device Timestamp;Record Type;Historic Glucose mmol/L;Scan Glucose mmol/L\nFreeStyle Libre 3;X;28-09-2026 23:59;0;7,9;\nFreeStyle Libre 3;X;13-09-2026 13:05;1;;5,5\n';
    const { readings } = parseLibreViewCsv(csv);
    expect(readings.map((r) => r.mg)).toEqual([Math.round(5.5 * MGDL_PER_MMOL), Math.round(7.9 * MGDL_PER_MMOL)]);
    expect(new Date(readings[1].t).getDate()).toBe(28);
  });
  it('rejects files that are not LibreView exports', () => {
    expect(() => parseLibreViewCsv('a,b\n1,2')).toThrow();
  });
});

describe('CSV export', () => {
  it('writes readings and markers in time order', () => {
    const csv = toCsv([{ t: T0, mg: 108 }], [{ t: T0 + 60e3, type: 'meal', amount: 45 }]).split('\r\n');
    expect(csv[0]).toBe('Date,Time,Glucose (mg/dL),Glucose (mmol/L),Marker,Amount,Amount unit,Detail');
    expect(csv[1]).toMatch(/,108,6\.0,,,,$/);
    expect(csv[2]).toMatch(/,,,Meal,45,g carbs,$/);
  });
});
