// Packs the phone app's files (workers/app/*) into workers/app-assets.js, which su94r-proxy serves
// at /app/. Edit the files in workers/app/, then run:  node scripts/build-app.mjs
// (tests/app.test.js fails when app-assets.js is out of date.)
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root = path.join(import.meta.dirname, '..');
const dir = path.join(root, 'workers', 'app');
const text = (f) => fs.readFileSync(path.join(dir, f), 'utf8').replace(/\r\n/g, '\n');
const b64 = (f) => fs.readFileSync(path.join(dir, f)).toString('base64');

export const MANIFEST = {
  id: '/app/',
  name: 'su94r',
  short_name: 'su94r',
  description: 'Live glucose, history, logging and the 14-day report, with every computer off.',
  start_url: '/app/',
  scope: '/app/',
  display: 'standalone',
  orientation: 'portrait',
  background_color: '#0d1117',
  theme_color: '#0d1117',
  icons: [
    { src: '/app/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: '/app/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: '/app/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    { src: '/app/icon.svg', sizes: 'any', type: 'image/svg+xml' },
  ],
};

export function buildAssets() {
  const page = text('page.html');
  const client = text('client.js');
  const sw = text('sw.js');
  const version = crypto.createHash('sha256').update(page + client + sw).digest('hex').slice(0, 12);
  const icons = { 'icon-192.png': b64('icon-192.png'), 'icon-512.png': b64('icon-512.png'), 'apple-touch-icon.png': b64('apple-touch-icon.png') };
  return `// Generated by scripts/build-app.mjs from workers/app/*. Do not edit here: edit those files and run
//   node scripts/build-app.mjs
export const APP_VERSION = ${JSON.stringify(version)};
export const APP_PAGE = ${JSON.stringify(page)};
export const APP_CLIENT = ${JSON.stringify(client)};
export const APP_SW = ${JSON.stringify(sw.replace("const CACHE = 'su94r-app-1';", `const CACHE = 'su94r-app-${version}';`))};
export const APP_ICON_SVG = ${JSON.stringify(text('icon.svg'))};
export const APP_MANIFEST = ${JSON.stringify(JSON.stringify(MANIFEST))};
export const APP_ICONS = ${JSON.stringify(icons, null, 1)};
`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(import.meta.filename)) {
  fs.writeFileSync(path.join(root, 'workers', 'app-assets.js'), buildAssets());
  console.log('workers/app-assets.js written');
}
